name: Rebuild website and make it live

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date; pwd; ls -l
      - run: bin/render
      - run: bin/live
